library(rvest)
library(dplyr)
library(stringr)
library(robotstxt)
url <- 'https://www.cardexpert.in/best-credit-cards-india/'
web <- read_html(url)
View(web)
hi=paths_allowed(url)
Card_Name <- web %>% html_nodes('td.has-text-align-right') %>% html_text()
View(Card_Name)
Max_rate <- web %>% html_nodes('.has-text-align-right+ td') %>% html_text()
View(Max_rate)
join_fees <- web %>% html_nodes('.has-text-align-center+ td.has-text-align-center') %>% html_text()
View(join_fees)
data_70= data.frame(Card_Name,Max_rate,join_fees)
View(data_70)
write.csv(data_70,"Card-list.csv")
